# Site settings
title:          Crawl3r
description:    "Skidding around the internet"
baseurl:        ""
url:            "https://crawl3r.github.io"

# Author
author:
  name:         Crawl3r
  url:          https://crawl3r.github.io
#  email:        

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
#disqus: